#pragma once
// Auto-generated HTML template for View.html
// The two markers %%INPUT_CSV%% and %%OUTPUT_CSV%% are replaced at runtime.
static const char VIEW_HTML_TEMPLATE[] =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"  <meta charset=\"UTF-8\" />\n"
"  <title>Polygon Before/After Viewer</title>\n"
"  <link href=\"https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Syne:wght@700;800&display=swap\" rel=\"stylesheet\">\n"
"  <style>\n"
"    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
"    :root {\n"
"      --bg:#0f0f11; --surface:#18181c; --border:#2a2a32;\n"
"      --accent:#c8f135; --dim:#555566; --text:#e8e8f0;\n"
"      --muted:#888899; --before:#4da9ff; --after:#ff6b6b;\n"
"    }\n"
"    body { background:var(--bg); color:var(--text); font-family:'DM Mono',monospace; min-height:100vh; display:flex; flex-direction:column; }\n"
"    header { padding:28px 40px 20px; border-bottom:1px solid var(--border); display:flex; align-items:baseline; gap:16px; }\n"
"    header h1 { font-family:'Syne',sans-serif; font-size:1.5rem; font-weight:800; letter-spacing:-0.02em; color:var(--accent); }\n"
"    header span { font-size:0.75rem; color:var(--muted); letter-spacing:0.08em; text-transform:uppercase; }\n"
"    #statusBar { padding:12px 40px; background:var(--surface); border-bottom:1px solid var(--border); display:flex; align-items:center; gap:24px; font-size:0.75rem; color:var(--muted); flex-wrap:wrap; }\n"
"    .stat { display:flex; gap:6px; align-items:center; }\n"
"    .stat .label { color:var(--dim); } .stat .val { color:var(--text); font-weight:500; }\n"
"    .dot { width:7px; height:7px; border-radius:50%; flex-shrink:0; }\n"
"    main { flex:1; display:grid; grid-template-columns:1fr 1fr; }\n"
"    .panel { display:flex; flex-direction:column; padding:24px; gap:12px; }\n"
"    .panel:first-child { border-right:1px solid var(--border); }\n"
"    .panel-header { display:flex; align-items:center; gap:10px; }\n"
"    .panel-header .dot { width:8px; height:8px; }\n"
"    .panel-header h2 { font-family:'Syne',sans-serif; font-size:0.85rem; font-weight:700; letter-spacing:0.1em; text-transform:uppercase; }\n"
"    .vcount { margin-left:auto; font-size:0.7rem; color:var(--muted); }\n"
"    .vcount span { color:var(--text); }\n"
"    canvas { width:100%; aspect-ratio:1; background:var(--surface); border:1px solid var(--border); border-radius:6px; display:block; }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <h1>POLY/SIMP</h1>\n"
"  <span>Polygon Simplifier &mdash; Before / After</span>\n"
"  <span style=\"margin-left:auto; color:var(--accent); opacity:0.7; font-size:0.7rem;\">%%FILENAME%%</span>\n"
"</header>\n"
"<div id=\"statusBar\">\n"
"  <div class=\"stat\"><div class=\"dot\" style=\"background:var(--before)\"></div>\n"
"    <span class=\"label\">before</span><span class=\"val\" id=\"statBefore\">-</span></div>\n"
"  <div class=\"stat\"><div class=\"dot\" style=\"background:var(--after)\"></div>\n"
"    <span class=\"label\">after</span><span class=\"val\" id=\"statAfter\">-</span></div>\n"
"  <div class=\"stat\"><span class=\"label\">reduction</span><span class=\"val\" id=\"statReduction\">-</span></div>\n"
"</div>\n"
"<main>\n"
"  <div class=\"panel\">\n"
"    <div class=\"panel-header\">\n"
"      <div class=\"dot\" style=\"background:var(--before)\"></div>\n"
"      <h2>Before</h2><span class=\"vcount\">vertices: <span id=\"vcBefore\">-</span></span>\n"
"    </div>\n"
"    <canvas id=\"beforeCanvas\" width=\"800\" height=\"800\"></canvas>\n"
"  </div>\n"
"  <div class=\"panel\">\n"
"    <div class=\"panel-header\">\n"
"      <div class=\"dot\" style=\"background:var(--after)\"></div>\n"
"      <h2>After</h2><span class=\"vcount\">vertices: <span id=\"vcAfter\">-</span></span>\n"
"    </div>\n"
"    <canvas id=\"afterCanvas\" width=\"800\" height=\"800\"></canvas>\n"
"  </div>\n"
"</main>\n"
"<script>\n"
"const INPUT_CSV  = `%%INPUT_CSV%%`;\n"
"const OUTPUT_CSV = `%%OUTPUT_CSV%%`;\n"
"function parseCSV(text) {\n"
"  const lines = text.trim().split(/\\r?\\n/);\n"
"  const rings = {};\n"
"  for (let i = 1; i < lines.length; i++) {\n"
"    const p = lines[i].split(',');\n"
"    if (p.length < 4) continue;\n"
"    const id = parseInt(p[0],10), x = parseFloat(p[2]), y = parseFloat(p[3]);\n"
"    if (isNaN(id)||isNaN(x)||isNaN(y)) continue;\n"
"    if (!rings[id]) rings[id] = [];\n"
"    rings[id].push({x, y});\n"
"  }\n"
"  return rings;\n"
"}\n"
"function countVerts(r) { return Object.values(r).reduce((s,a)=>s+a.length,0); }\n"
"function getBounds(sets) {\n"
"  let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;\n"
"  for (const rings of sets)\n"
"    for (const ring of Object.values(rings))\n"
"      for (const p of ring) {\n"
"        if(p.x<minX)minX=p.x; if(p.x>maxX)maxX=p.x;\n"
"        if(p.y<minY)minY=p.y; if(p.y>maxY)maxY=p.y;\n"
"      }\n"
"  if(!isFinite(minX)){minX=minY=0;maxX=maxY=1;}\n"
"  return {minX,minY,maxX,maxY};\n"
"}\n"
"function drawPanel(id, rings, bounds, color) {\n"
"  const canvas=document.getElementById(id), ctx=canvas.getContext('2d');\n"
"  const W=canvas.width, H=canvas.height;\n"
"  ctx.clearRect(0,0,W,H);\n"
"  const pad=50, w=Math.max(bounds.maxX-bounds.minX,1e-9), h=Math.max(bounds.maxY-bounds.minY,1e-9);\n"
"  const scale=Math.min((W-2*pad)/w,(H-2*pad)/h);\n"
"  const mp=p=>({x:pad+(p.x-bounds.minX)*scale, y:H-(pad+(p.y-bounds.minY)*scale)});\n"
"  const ids=Object.keys(rings).map(Number).sort((a,b)=>a-b);\n"
"  ctx.save(); ctx.beginPath();\n"
"  for (const rid of ids) {\n"
"    const ring=rings[rid]; if(!ring.length) continue;\n"
"    const s=mp(ring[0]); ctx.moveTo(s.x,s.y);\n"
"    for(let i=1;i<ring.length;i++){const m=mp(ring[i]);ctx.lineTo(m.x,m.y);}\n"
"    ctx.closePath();\n"
"  }\n"
"  ctx.fillStyle=color+'18'; ctx.fill('evenodd'); ctx.restore();\n"
"  for(let idx=0;idx<ids.length;idx++){\n"
"    const ring=rings[ids[idx]]; if(!ring.length) continue;\n"
"    const ec=idx===0?color:'#ff9f43';\n"
"    ctx.beginPath();\n"
"    for(let i=0;i<ring.length;i++){const m=mp(ring[i]);i===0?ctx.moveTo(m.x,m.y):ctx.lineTo(m.x,m.y);}\n"
"    ctx.closePath(); ctx.strokeStyle=ec; ctx.lineWidth=idx===0?2:1.5; ctx.stroke();\n"
"    for(const p of ring){\n"
"      const m=mp(p); ctx.beginPath(); ctx.arc(m.x,m.y,idx===0?3.5:3,0,Math.PI*2);\n"
"      ctx.fillStyle=ec; ctx.fill();\n"
"    }\n"
"  }\n"
"}\n"
"const br=parseCSV(INPUT_CSV), ar=parseCSV(OUTPUT_CSV);\n"
"const bounds=getBounds([br,ar]);\n"
"drawPanel('beforeCanvas',br,bounds,'#4da9ff');\n"
"drawPanel('afterCanvas', ar,bounds,'#ff6b6b');\n"
"const nb=countVerts(br), na=countVerts(ar);\n"
"document.getElementById('statBefore').textContent=nb;\n"
"document.getElementById('statAfter').textContent=na;\n"
"document.getElementById('vcBefore').textContent=nb;\n"
"document.getElementById('vcAfter').textContent=na;\n"
"document.getElementById('statReduction').textContent=(((nb-na)/nb)*100).toFixed(1)+'%';\n"
"</script>\n"
"</body>\n"
"</html>\n";